### ISSUE TITLE
Uncaught ReferenceError: Webcam is not defined

### ISSUE THREAD

**Issue by TNAJanssen** [foxnewsnetwork/ember-webcam-input#1]
And the documentation is outdated, you use the wrong syntax

**Comment by foxnewsnetwork** [comment]
Thanks for head's up, I will look into it.

**Comment by foxnewsnetwork** [comment]
So the issue was `index.js` just needed a `included` hook so ember automatically knows to include webcamjs into your app without you having to include the `app.import("bower_components/webcam.js")` directive into your `ember-cli-build.js`

If you try it now, everything should be working. But let me know if it doesn't.
